/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialogue;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Gabriel,Julie,Louis,Yoann,Dina,Mariama
 */
public class MainFrame extends javax.swing.JFrame{

    /**
     * Creates new form main
     * @throws java.net.URISyntaxException
     * @throws java.io.IOException
     */
    public MainFrame() throws URISyntaxException, IOException {
        initComponents();
        initJetons();
        setTitle("Panic'Pirate");
        BufferedImage image = ImageIO.read(new File(getClass().getResource("/Images/logo_pirate.png").toURI()));
        this.setIconImage(image);
        
        affichageDes1.setVisible(false);
        cases[0] = case1;
        cases[1] = case2;
        cases[2] = case3;
        cases[3] = case4;
        cases[4] = case5;
        cases[5] = case6;
        cases[6] = case7;
        cases[7] = case8;
        cases[8] = case9;
        cases[9] = case10;
        cases[10] = case11;
        cases[11] = case12;
        cases[12] = case13;
        cases[13] = case14;
        cases[14] = case15;
        cases[15] = case16;
        cases[16] = case17;
        cases[17] = case18;
        cases[18] = case19;
        cases[19] = case20;
        cases[20] = case21;
        cases[21] = case22;
        cases[22] = case23;
        cases[23] = case24;
        cases[24] = case25;
        cases[25] = case26;
        cases[26] = case27;
        cases[27] = case28;
        cases[28] = case29;
        cases[29] = case30;
        cases[29].loadImage("/Images/case.png");
        
        for(int i = 1; i<=30; i++){
            cases[i-1].setNumCase(i);
        }
   
        jeton1.setLocation(15, 15);
        jeton2.setLocation(50, 50);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        historique = new javax.swing.JTextArea();
        imagePirate3 = new dialogue.ImagePirate();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        try {
            vieJ1 = new dialogue.BarreDeVie();
        } catch (java.net.URISyntaxException e1) {
            e1.printStackTrace();
        }
        imagePirate1 = new dialogue.ImagePirate();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        try {
            vieJ2 = new dialogue.BarreDeVie();
        } catch (java.net.URISyntaxException e1) {
            e1.printStackTrace();
        }
        imagePirate2 = new dialogue.ImagePirate();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        affichageDes1 = new dialogue.AffichageDes();
        jeton2 = new dialogue.Jeton();
        jeton1 = new dialogue.Jeton();
        Plateauihm = new javax.swing.JPanel();
        case1 = new dialogue.Case();
        case2 = new dialogue.Case();
        case3 = new dialogue.Case();
        case4 = new dialogue.Case();
        case5 = new dialogue.Case();
        case6 = new dialogue.Case();
        case7 = new dialogue.Case();
        case8 = new dialogue.Case();
        case9 = new dialogue.Case();
        case10 = new dialogue.Case();
        case11 = new dialogue.Case();
        case12 = new dialogue.Case();
        case13 = new dialogue.Case();
        case14 = new dialogue.Case();
        case15 = new dialogue.Case();
        case16 = new dialogue.Case();
        case17 = new dialogue.Case();
        case18 = new dialogue.Case();
        case19 = new dialogue.Case();
        case20 = new dialogue.Case();
        case21 = new dialogue.Case();
        case22 = new dialogue.Case();
        case23 = new dialogue.Case();
        case24 = new dialogue.Case();
        case25 = new dialogue.Case();
        case26 = new dialogue.Case();
        case27 = new dialogue.Case();
        case28 = new dialogue.Case();
        case29 = new dialogue.Case();
        case30 = new dialogue.Case();
        fondEcran1 = new dialogue.FondEcran();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(242, 222, 193));
        jButton1.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jButton1.setText("Lancer dés");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        historique.setEditable(false);
        historique.setBackground(new java.awt.Color(242, 222, 193));
        historique.setColumns(20);
        historique.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        historique.setRows(5);
        jScrollPane1.setViewportView(historique);

        javax.swing.GroupLayout imagePirate3Layout = new javax.swing.GroupLayout(imagePirate3);
        imagePirate3.setLayout(imagePirate3Layout);
        imagePirate3Layout.setHorizontalGroup(
            imagePirate3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        imagePirate3Layout.setVerticalGroup(
            imagePirate3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(imagePirate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagePirate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wiliam l'ecorcheur");

        vieJ1.setOpaque(false);

        javax.swing.GroupLayout vieJ1Layout = new javax.swing.GroupLayout(vieJ1);
        vieJ1.setLayout(vieJ1Layout);
        vieJ1Layout.setHorizontalGroup(
            vieJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        vieJ1Layout.setVerticalGroup(
            vieJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagePirate1Layout = new javax.swing.GroupLayout(imagePirate1);
        imagePirate1.setLayout(imagePirate1Layout);
        imagePirate1Layout.setHorizontalGroup(
            imagePirate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        imagePirate1Layout.setVerticalGroup(
            imagePirate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(vieJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagePirate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePirate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(vieJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(124, 502));

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Wiliam l'ecorcheur");

        vieJ2.setOpaque(false);

        javax.swing.GroupLayout vieJ2Layout = new javax.swing.GroupLayout(vieJ2);
        vieJ2.setLayout(vieJ2Layout);
        vieJ2Layout.setHorizontalGroup(
            vieJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        vieJ2Layout.setVerticalGroup(
            vieJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imagePirate2Layout = new javax.swing.GroupLayout(imagePirate2);
        imagePirate2.setLayout(imagePirate2Layout);
        imagePirate2Layout.setHorizontalGroup(
            imagePirate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagePirate2Layout.setVerticalGroup(
            imagePirate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(vieJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(imagePirate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePirate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vieJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        affichageDes1.setBackground(new java.awt.Color(102, 102, 102));
        affichageDes1.setOpaque(false);
        affichageDes1.setPreferredSize(new java.awt.Dimension(269, 118));

        javax.swing.GroupLayout affichageDes1Layout = new javax.swing.GroupLayout(affichageDes1);
        affichageDes1.setLayout(affichageDes1Layout);
        affichageDes1Layout.setHorizontalGroup(
            affichageDes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        affichageDes1Layout.setVerticalGroup(
            affichageDes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jLayeredPane1.add(affichageDes1);
        affichageDes1.setBounds(200, 120, 269, 118);

        jeton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jeton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jeton2MouseDragged(evt);
            }
        });
        jeton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jeton2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jeton2Layout = new javax.swing.GroupLayout(jeton2);
        jeton2.setLayout(jeton2Layout);
        jeton2Layout.setHorizontalGroup(
            jeton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jeton2Layout.setVerticalGroup(
            jeton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jeton2);
        jeton2.setBounds(287, 198, 40, 40);

        jeton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jeton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jeton1MouseDragged(evt);
            }
        });
        jeton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jeton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jeton1Layout = new javax.swing.GroupLayout(jeton1);
        jeton1.setLayout(jeton1Layout);
        jeton1Layout.setHorizontalGroup(
            jeton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jeton1Layout.setVerticalGroup(
            jeton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jeton1);
        jeton1.setBounds(325, 248, 40, 40);

        Plateauihm.setOpaque(false);
        Plateauihm.setPreferredSize(new java.awt.Dimension(500, 582));
        Plateauihm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        case1.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case1Layout = new javax.swing.GroupLayout(case1);
        case1.setLayout(case1Layout);
        case1Layout.setHorizontalGroup(
            case1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case1Layout.setVerticalGroup(
            case1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        case2.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case2Layout = new javax.swing.GroupLayout(case2);
        case2.setLayout(case2Layout);
        case2Layout.setHorizontalGroup(
            case2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case2Layout.setVerticalGroup(
            case2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        case3.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case3Layout = new javax.swing.GroupLayout(case3);
        case3.setLayout(case3Layout);
        case3Layout.setHorizontalGroup(
            case3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case3Layout.setVerticalGroup(
            case3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        case4.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case4Layout = new javax.swing.GroupLayout(case4);
        case4.setLayout(case4Layout);
        case4Layout.setHorizontalGroup(
            case4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case4Layout.setVerticalGroup(
            case4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        case5.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case5Layout = new javax.swing.GroupLayout(case5);
        case5.setLayout(case5Layout);
        case5Layout.setHorizontalGroup(
            case5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case5Layout.setVerticalGroup(
            case5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        case6.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case6Layout = new javax.swing.GroupLayout(case6);
        case6.setLayout(case6Layout);
        case6Layout.setHorizontalGroup(
            case6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case6Layout.setVerticalGroup(
            case6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        case7.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case7Layout = new javax.swing.GroupLayout(case7);
        case7.setLayout(case7Layout);
        case7Layout.setHorizontalGroup(
            case7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case7Layout.setVerticalGroup(
            case7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        case8.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case8Layout = new javax.swing.GroupLayout(case8);
        case8.setLayout(case8Layout);
        case8Layout.setHorizontalGroup(
            case8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case8Layout.setVerticalGroup(
            case8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        case9.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case9Layout = new javax.swing.GroupLayout(case9);
        case9.setLayout(case9Layout);
        case9Layout.setHorizontalGroup(
            case9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case9Layout.setVerticalGroup(
            case9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        case10.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case10Layout = new javax.swing.GroupLayout(case10);
        case10.setLayout(case10Layout);
        case10Layout.setHorizontalGroup(
            case10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case10Layout.setVerticalGroup(
            case10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        case11.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case11Layout = new javax.swing.GroupLayout(case11);
        case11.setLayout(case11Layout);
        case11Layout.setHorizontalGroup(
            case11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case11Layout.setVerticalGroup(
            case11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        case12.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case12Layout = new javax.swing.GroupLayout(case12);
        case12.setLayout(case12Layout);
        case12Layout.setHorizontalGroup(
            case12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case12Layout.setVerticalGroup(
            case12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        case13.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case13Layout = new javax.swing.GroupLayout(case13);
        case13.setLayout(case13Layout);
        case13Layout.setHorizontalGroup(
            case13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case13Layout.setVerticalGroup(
            case13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        case14.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case14Layout = new javax.swing.GroupLayout(case14);
        case14.setLayout(case14Layout);
        case14Layout.setHorizontalGroup(
            case14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case14Layout.setVerticalGroup(
            case14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        case15.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case15Layout = new javax.swing.GroupLayout(case15);
        case15.setLayout(case15Layout);
        case15Layout.setHorizontalGroup(
            case15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case15Layout.setVerticalGroup(
            case15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case15, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 198, -1, -1));

        case16.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case16Layout = new javax.swing.GroupLayout(case16);
        case16.setLayout(case16Layout);
        case16Layout.setHorizontalGroup(
            case16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case16Layout.setVerticalGroup(
            case16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 198, -1, -1));

        case17.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case17Layout = new javax.swing.GroupLayout(case17);
        case17.setLayout(case17Layout);
        case17Layout.setHorizontalGroup(
            case17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case17Layout.setVerticalGroup(
            case17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        case18.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case18Layout = new javax.swing.GroupLayout(case18);
        case18.setLayout(case18Layout);
        case18Layout.setHorizontalGroup(
            case18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case18Layout.setVerticalGroup(
            case18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        case19.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case19Layout = new javax.swing.GroupLayout(case19);
        case19.setLayout(case19Layout);
        case19Layout.setHorizontalGroup(
            case19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case19Layout.setVerticalGroup(
            case19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        case20.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case20Layout = new javax.swing.GroupLayout(case20);
        case20.setLayout(case20Layout);
        case20Layout.setHorizontalGroup(
            case20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case20Layout.setVerticalGroup(
            case20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        case21.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case21Layout = new javax.swing.GroupLayout(case21);
        case21.setLayout(case21Layout);
        case21Layout.setHorizontalGroup(
            case21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case21Layout.setVerticalGroup(
            case21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        case22.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case22Layout = new javax.swing.GroupLayout(case22);
        case22.setLayout(case22Layout);
        case22Layout.setHorizontalGroup(
            case22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case22Layout.setVerticalGroup(
            case22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        case23.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case23Layout = new javax.swing.GroupLayout(case23);
        case23.setLayout(case23Layout);
        case23Layout.setHorizontalGroup(
            case23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case23Layout.setVerticalGroup(
            case23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        case24.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case24Layout = new javax.swing.GroupLayout(case24);
        case24.setLayout(case24Layout);
        case24Layout.setHorizontalGroup(
            case24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case24Layout.setVerticalGroup(
            case24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        case25.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case25Layout = new javax.swing.GroupLayout(case25);
        case25.setLayout(case25Layout);
        case25Layout.setHorizontalGroup(
            case25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case25Layout.setVerticalGroup(
            case25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        case26.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case26Layout = new javax.swing.GroupLayout(case26);
        case26.setLayout(case26Layout);
        case26Layout.setHorizontalGroup(
            case26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case26Layout.setVerticalGroup(
            case26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        case27.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case27Layout = new javax.swing.GroupLayout(case27);
        case27.setLayout(case27Layout);
        case27Layout.setHorizontalGroup(
            case27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case27Layout.setVerticalGroup(
            case27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        case28.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case28Layout = new javax.swing.GroupLayout(case28);
        case28.setLayout(case28Layout);
        case28Layout.setHorizontalGroup(
            case28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case28Layout.setVerticalGroup(
            case28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        case29.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case29Layout = new javax.swing.GroupLayout(case29);
        case29.setLayout(case29Layout);
        case29Layout.setHorizontalGroup(
            case29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case29Layout.setVerticalGroup(
            case29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        case30.setPreferredSize(new java.awt.Dimension(90, 90));

        javax.swing.GroupLayout case30Layout = new javax.swing.GroupLayout(case30);
        case30.setLayout(case30Layout);
        case30Layout.setHorizontalGroup(
            case30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        case30Layout.setVerticalGroup(
            case30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        Plateauihm.add(case30, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jLayeredPane1.add(Plateauihm);
        Plateauihm.setBounds(6, 6, 652, 486);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        javax.swing.GroupLayout fondEcran1Layout = new javax.swing.GroupLayout(fondEcran1);
        fondEcran1.setLayout(fondEcran1Layout);
        fondEcran1Layout.setHorizontalGroup(
            fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        fondEcran1Layout.setVerticalGroup(
            fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jLayeredPane2.add(fondEcran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -1, 940, 650));

        jMenu1.setText("Quit");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Restart");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        SwingUtilities.invokeLater(() -> {
            try {
                new MenuFrame().setVisible(true);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

 
    public void setDialog(Dialog dialog) {
        this.dialog = dialog;
    }
    
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(jButton1.isEnabled()){
            affichageDes1.setVisible(true);
            dialog.finLancerDes();
        }  
    }//GEN-LAST:event_jButton1MouseClicked

    
    private void jeton2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeton2MouseDragged
        if(jeton2.isEnabled())
            moveJeton(jeton2, evt.getPoint());
    }//GEN-LAST:event_jeton2MouseDragged

    private void jeton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeton1MouseDragged
        if(jeton1.isEnabled())
            moveJeton(jeton1, evt.getPoint());
    }//GEN-LAST:event_jeton1MouseDragged

    Point posPirate1;
    Point posPirate2;    
    private void jeton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeton1MouseReleased
        if(jeton1.isEnabled()){
            if(!dialog.verifierDeplacement(inCase(jeton1))){
                jeton1.setLocation(posPirate1);
            }
        }
    }//GEN-LAST:event_jeton1MouseReleased

    private void jeton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeton2MouseReleased
        if(jeton2.isEnabled()){
            if(!dialog.verifierDeplacement(inCase(jeton2))){
                    jeton2.setLocation(posPirate2);
            }
        }
    }//GEN-LAST:event_jeton2MouseReleased
    
    private void initJetons(){
        jeton1.setImage("/Images/craneBleu.png");
        jeton2.setImage("/Images/craneRouge.png");
        jeton1.setEnabled(false);
        jeton2.setEnabled(false);
    }

    private void moveJeton(Jeton jeton, Point p){
        Point pos = SwingUtilities.convertPoint(jeton, p, Plateauihm);
        pos.setLocation(pos.getX() - (jeton.getWidth()/2), pos.getY() - (jeton.getHeight()/2));
        jeton.setLocation(pos);         
    }
    
    private int inCase(Jeton jeton){
        for (int i = 0; i < 30; i++) {
          if(SwingUtilities.isRectangleContainingRectangle(cases[i].getBounds(), jeton.getBounds()))
              return i+1;
        }
        return -1;
    }
    
    protected void initPirateImages(BufferedImage i1, BufferedImage i2, String j1Name, String j2Name){
        imagePirate1.setImagePirate(i1);
        imagePirate2.setImagePirate(i2);
        jLabel1.setText(j1Name);
        jLabel2.setText(j2Name);
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        
    }
    

    
    public void debloquerDes(){
        jButton1.setEnabled(true);
    }
    
    Timer timer;
    Dialog dialog;
    private Case[] cases = new Case[30];
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Plateauihm;
    private dialogue.AffichageDes affichageDes1;
    private dialogue.Case case1;
    private dialogue.Case case10;
    private dialogue.Case case11;
    private dialogue.Case case12;
    private dialogue.Case case13;
    private dialogue.Case case14;
    private dialogue.Case case15;
    private dialogue.Case case16;
    private dialogue.Case case17;
    private dialogue.Case case18;
    private dialogue.Case case19;
    private dialogue.Case case2;
    private dialogue.Case case20;
    private dialogue.Case case21;
    private dialogue.Case case22;
    private dialogue.Case case23;
    private dialogue.Case case24;
    private dialogue.Case case25;
    private dialogue.Case case26;
    private dialogue.Case case27;
    private dialogue.Case case28;
    private dialogue.Case case29;
    private dialogue.Case case3;
    private dialogue.Case case30;
    private dialogue.Case case4;
    private dialogue.Case case5;
    private dialogue.Case case6;
    private dialogue.Case case7;
    private dialogue.Case case8;
    private dialogue.Case case9;
    private dialogue.FondEcran fondEcran1;
    private javax.swing.JTextArea historique;
    private dialogue.ImagePirate imagePirate1;
    private dialogue.ImagePirate imagePirate2;
    private dialogue.ImagePirate imagePirate3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private dialogue.Jeton jeton1;
    private dialogue.Jeton jeton2;
    private dialogue.BarreDeVie vieJ1;
    private dialogue.BarreDeVie vieJ2;
    // End of variables declaration//GEN-END:variables

    
    public void indiquerTour(BufferedImage image, String nomPirate) {
        historique.append(nomPirate+" est en train de jouer ! \n");
        posPirate1 = jeton1.getLocation();
        posPirate2 = jeton2.getLocation();
        imagePirate3.setImagePirate(image);
    }

    
    public void afficherDes(int val1, int val2) {
        affichageDes1.Afficher(val1, val2);
        int res = val1 + val2;
        jButton1.setEnabled(false);
        timer = new Timer(3000, (ActionEvent e) -> {
                    historique.append("Faites "+res+" pas en avant.\n");
                    affichageDes1.setVisible(false);
                    timer.stop();
        });
        
        timer.start();
    }

    
    public void bloquerJetons() {
        jeton1.setEnabled(false);
        jeton2.setEnabled(false);
        
    }

    
    public void deplacerPirate(int joueurCourant) {
        if(joueurCourant == 1){
            jeton1.setEnabled(true);
        }else{            
            jeton2.setEnabled(true);
        }
    }

    
    public void caseNormale() {
        historique.append("Rien ne se passe \n");
    }

   
    public void caseBombe(int vie, int joueurCourant, String nom, int pos) {
        cases[pos-1].loadImage("/Images/bombe.png");
        
        historique.append("BOUM ! vous êtes tombé sur une bombe...\n");
        historique.append(nom+" a actuellement "+vie+" points de vie.\n");
        if(joueurCourant==1){
            try {
                vieJ1.setVie(vie);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(joueurCourant==2){
            try {
                vieJ2.setVie(vie);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.repaint();
    }

    public void caseQuestion(String reaction, int vie, int joueurCourant, int pos, String nom) {
        cases[pos-1].loadImage("/Images/sage_question.png");
        
        historique.append(reaction+"\n");
         historique.append(nom+" a actuellement "+vie+" points de vie.\n");
        
        
        if(joueurCourant==1){
            try {
                vieJ1.setVie(vie);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        if(joueurCourant==2){
            try {
                vieJ2.setVie(vie);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.repaint();
        
        
    }

    public int poserQuestion(int numCase, String question, String reponse1, String reponse2) {
        String[] reponses = {reponse1, reponse2};
        int reponse;
        do{
            reponse = JOptionPane.showOptionDialog(this, question,"Question",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, reponses,null);
        }while(reponse == -1);
        return reponse;
    }

    public void annoncerVainqueur(String nomVainqueur) {
        JOptionPane.showConfirmDialog(this, nomVainqueur+" à vaincu son adversaire ! Bravo au nouveau capitaine !","Fin de la partie",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null);
        
        SwingUtilities.invokeLater(() -> {
            try {
                new MenuFrame().setVisible(true);
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        this.dispose();
    }
}
