/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialogue;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;

/**
 *
 * @author gabri
 */
public class MenuFrame extends javax.swing.JFrame {
    
    public JPanel[] tableau = new JPanel[2];

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() throws URISyntaxException, IOException {
        initComponents();
        jButton1.setOpaque(false);
        this.add(fondEcran1, BorderLayout.CENTER);
        BufferedImage image = ImageIO.read(new File(getClass().getResource("/Images/logo_pirate.png").toURI()));
        this.setIconImage(image);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondEcran1 = new dialogue.FondEcran();
        pirate12 = new dialogue.Pirate1();
        pirate21 = new dialogue.Pirate2();
        pirate31 = new dialogue.Pirate3();
        pirate41 = new dialogue.Pirate4();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pirate12.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                pirate1Handler(e);
            }
        });
        pirate21.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                pirate2Handler(e);
            }
        });
        pirate31.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                pirate3Handler(e);
            }
        });
        pirate41.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                pirate4Handler(e);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panic'Pirate");
        setBackground(new java.awt.Color(60, 242, 242));
        setFocusableWindowState(false);
        setResizable(false);

        javax.swing.GroupLayout pirate12Layout = new javax.swing.GroupLayout(pirate12);
        pirate12.setLayout(pirate12Layout);
        pirate12Layout.setHorizontalGroup(
                pirate12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pirate12Layout.setVerticalGroup(
                pirate12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pirate21Layout = new javax.swing.GroupLayout(pirate21);
        pirate21.setLayout(pirate21Layout);
        pirate21Layout.setHorizontalGroup(
                pirate21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pirate21Layout.setVerticalGroup(
                pirate21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pirate31Layout = new javax.swing.GroupLayout(pirate31);
        pirate31.setLayout(pirate31Layout);
        pirate31Layout.setHorizontalGroup(
                pirate31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pirate31Layout.setVerticalGroup(
                pirate31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 164, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pirate41Layout = new javax.swing.GroupLayout(pirate41);
        pirate41.setLayout(pirate41Layout);
        pirate41Layout.setHorizontalGroup(
                pirate41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pirate41Layout.setVerticalGroup(
                pirate41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aria l'Ecarlate");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setBackground(new java.awt.Color(153, 102, 0));
        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("William l'Ecorcheur");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel3.setBackground(new java.awt.Color(204, 204, 0));
        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setLabelFor(pirate41);
        jLabel3.setText("Callic  O'Jack");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Luna l'Impitoyable");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButton1.setText("START NEW GAME");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondEcran1Layout = new javax.swing.GroupLayout(fondEcran1);
        fondEcran1.setLayout(fondEcran1Layout);
        fondEcran1Layout.setHorizontalGroup(
                fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fondEcran1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(pirate12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pirate21, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pirate31, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pirate41, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondEcran1Layout.createSequentialGroup()
                                .addContainerGap(288, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(274, 274, 274))
        );
        fondEcran1Layout.setVerticalGroup(
                fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fondEcran1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pirate41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pirate31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pirate21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pirate12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(fondEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(137, Short.MAX_VALUE))
        );

        getContentPane().add(fondEcran1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    public void pirate1Handler(MouseEvent evt){
        if(SwingUtilities.isLeftMouseButton(evt)){
            if(tableau[0]!= null){
                tableau[0].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[1] == pirate12) tableau[1] = null;
            tableau[0] = pirate12;
            tableau[0].setBorder(new LineBorder(Color.blue, 3));
        }else{
            if(tableau[1]!= null){
                tableau[1].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[0] == pirate12) tableau[0] = null;
            tableau[1] = pirate12;
            tableau[1].setBorder(new LineBorder(Color.red, 3));
        }
    }
    
    public void pirate2Handler(MouseEvent evt){
        if(SwingUtilities.isLeftMouseButton(evt)){
            if(tableau[0]!= null){
                tableau[0].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[1] == pirate21) tableau[1] = null;
            tableau[0] = pirate21;
            tableau[0].setBorder(new LineBorder(Color.blue, 3));
        }else{
            if(tableau[1]!= null){
                tableau[1].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[0] == pirate21) tableau[0] = null;
            tableau[1] = pirate21;
            tableau[1].setBorder(new LineBorder(Color.red, 3));
        }
    }
    
    public void pirate3Handler(MouseEvent evt){
        if(SwingUtilities.isLeftMouseButton(evt)){
            if(tableau[0]!= null){
                tableau[0].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[1] == pirate31) tableau[1] = null;
            tableau[0] = pirate31;
            tableau[0].setBorder(new LineBorder(Color.blue, 3));
        }else{
            if(tableau[1]!= null){
                tableau[1].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[0] == pirate31) tableau[0] = null;
            tableau[1] = pirate31;
            tableau[1].setBorder(new LineBorder(Color.red, 3));
        }
    }
    
    public void pirate4Handler(MouseEvent evt){
        if(SwingUtilities.isLeftMouseButton(evt)){
            if(tableau[0]!= null){
                tableau[0].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[1] == pirate41) tableau[1] = null;
            tableau[0] = pirate41;
            tableau[0].setBorder(new LineBorder(Color.blue, 3));
        }else{
            if(tableau[1]!= null){
                tableau[1].setBorder(new LineBorder(Color.black, 3));
            }
            if (tableau[0] == pirate41) tableau[0] = null;
            tableau[1] = pirate41;
            tableau[1].setBorder(new LineBorder(Color.red, 3));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuFrame().setVisible(true);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dialogue.FondEcran fondEcran1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private dialogue.Pirate1 pirate12;
    private dialogue.Pirate2 pirate21;
    private dialogue.Pirate3 pirate31;
    private dialogue.Pirate4 pirate41;
    // End of variables declaration//GEN-END:variables
}
