/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author GBL4455A
 */
public class AffichageDes extends javax.swing.JPanel {

    /**
     * Creates new form Des
     */
    BufferedImage[] images = new BufferedImage[6];
    BufferedImage imageAAfficher;
    Timer timer;
    int currentIndex = 0;
    public AffichageDes() {
        initComponents();
        try {
            for (int i = 0; i < 6; i++) {
                String n = i+1 + "";
                images[i] = ImageIO.read(new File("Z:\\Projet Pirate\\ProjetPirate\\src\\main\\java\\images\\" + n +".PNG"));
                timer = new Timer(100, (ActionEvent e) -> {
                    if (currentIndex < images.length) {
                        imageAAfficher = images[currentIndex];
                        System.out.println("image chargée");
                        repaint();
                        currentIndex++;
                    }
                });
            }

        } catch (IOException ex) {
            System.out.println("Erreur du chargement de l'image");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Afficher();
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    void Afficher(){
        timer.start();
    }    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (imageAAfficher != null) {
            g.drawImage(imageAAfficher, 0, 0, this);
            System.out.println("image affichée");

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
